### ISSUE TITLE
3 legend controls that are actually implemented differently.

### ISSUE THREAD

**Issue by joanma747** [opengeospatial/D012-MapML_Engineering_Report#28]
For a MapML layer, we have 3 controls in the legend that are different:
* See issue 15 "Alternate named styles #15" (that is a `<link rel=style>`)
   * This might be also be useful for CRS negotiation
* Selector of time, band... (that is an input) (see issue #29)
* Opacity that is added automatically

**Comment by prushforth** [comment]
I'm not sure why you think this is an issue.   Opacity being a slider seems like a natural fit.  The word "opacity" will have to be replaced by a symbol or something.  It needs to be internationalized, as well as accessible if it will be implemented by the browser by default.

The select element was implemented as such because it is useful and also simple.  Other input types are either not as useful or not as simple.  Deciding what inputs to support is probably beyond what we can accomplish without browser involvement anyway.  Ideally we'll have enough inputs that will 'cover' as many existing / as much existing services and data as possible.  

As for what selector to use for alternate named styles, a radio button seemed like a reasonable choice, but perhaps you think a select would do as well?  

As far as CRS negotiation goes, I don't think the user needs to be involved in that selection, it is a user-agent level decision, in my opinion.  So it doesn't need a user interface, only a decision tree to be executed by the user agent.

**Comment by prushforth** [comment]
Hmm.  I know that changing projections as you zoom in or out can be a valuable feature and my organizations web maps do that in some instances, but they do it automatically, based on the judgement of the cartographer, not the user.
