### ISSUE TITLE
Events triggered by user actions in MAPS4HTML

### ISSUE THREAD

**Issue by joanma747** [opengeospatial/D012-MapML_Engineering_Report#34]
At this moment, if the user changes the pan or zoom, the JavaScript of the page is not informed and cannot known about it. It could be good that the JavaScript is aware of the position and zoom of the map in order to synchronize the content of the page accordingly.

The page
/opengeospatial/D012-MapML_Engineering_Report/blob/master/9-events.adoc

contains a proposal of event enrichment for MapML that mainly consists in having some onchange onclick onload and onerror events associated with <map> and <layer> to inform the JavaScript that something happens on the map.

Can we discuss about it?

**Comment by prushforth** [comment]
We sure can!  In fact, the custom element does emit events, although because there hasn't been a lot of programming done with the custom element yet, the set of events supported is not grounded in what might be actually needed, or work for that matter (because that code is not covered by tests yet).  If you look at the bottom of the [web-map.html](https://github.com/Maps4HTML/Web-Map-Custom-Element/blob/master/web-map.html) source file, you'll see the list of events that are emitted, including 'move', 'moveend', 'zoom', 'zoomend', etc.

I'll have a look at the proposal, and we can discuss briefly at the meeting tomorrow and see what path we can take.

**Comment by joanma747** [comment]
I'm closing this discussion and moving it to the document. We can always reopen it if we have more time/energy to favor this line of development.
